analyzer:
  kafka:
    user-actions-properties:
      "bootstrap.servers": localhost:9092
      "group.id": analyzer-user-actions-group
      "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
      "value.deserializer": kafka.serializer.UserActionDeserializer
    event-similarity-properties:
      "bootstrap.servers": localhost:9092
      "group.id": analyzer-event-similarity-group
      "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
      "value.deserializer": kafka.serializer.EventSimilarityDeserializer
    topics:
      user-actions: stats.user-actions.v1
      event-similarity: stats.events-similarity.v1


grpc:
  server:
    port: 0
  client:
    analyzer:
      address: 'discovery:///analyzer'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  application:
    name: analyzer
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:h2:mem:analyzer
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    lease-renewal-interval-in-seconds: 10

server:
  port: 9999