server:
  port: 0

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/core/{application}
            - classpath:config/stats/{application}
            - classpath:config/infra/{application}
      fail-fast: true
      retry:
        use-random-policy: true
        max-interval: 6000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka