collector:
  kafka:
    producer-properties:
      "bootstrap.servers": kafka:29092
      "client.id": stats.collector
      "key.serializer": org.apache.kafka.common.serialization.StringSerializer
      "value.serializer": kafka.serializer.GeneralAvroSerializer
    topics:
      user-actions: stats.user-actions.v1

grpc:
  server:
    port: 0
  client:
    collector:
      address: 'discovery:///collector'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext


logging:
  level:
    org:
      zalando:
        logbook: TRACE