aggregator:
  kafka:
    producer-properties:
      "bootstrap.servers": kafka:29092
      "key.serializer": org.apache.kafka.common.serialization.StringSerializer
      "value.serializer": kafka.serializer.GeneralAvroSerializer
    consumer-properties:
      "bootstrap.servers": kafka:29092
      "group.id": aggregator-group
      "key.deserializer": org.apache.kafka.common.serialization.StringDeserializer
      "value.deserializer": kafka.serializer.UserActionDeserializer

    topics:
      user-actions: stats.user-actions.v1
      events-similarity: stats.events-similarity.v1

  user:
    action:
      weight:
        view: 0.4
        register: 0.8
        like: 1.0

logging:
  level:
    org:
      zalando:
        logbook: TRACE