spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewm_request
    username: sa
    password: password
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

server:
  port: 0

service:
  stats-server: stats-server