spring:
  application:
    name: event-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm-main
    username: user
    password: password

server:
  port: 0

grpc:
  client:
    analyzer:
      address: "discovery:///analyzer"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT
    collector:
      address: "discovery:///collector"
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: PLAINTEXT