spring:
  application:
    name: main-service
  config:
    import: "configserver:"
cloud:
  config:
    fail-fast: true
    discovery:
      enabled: true
      serviceId: config-server
    retry:
      useRandomPolicy: true
      max-interval: 6000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/